language: php
php:
  - '7.0'
  - '7.1'
sudo: false
before_script:
    - composer self-update
    - composer clear-cache
    - composer install --prefer-source --no-interaction
script: vendor/bin/phpunit